### ISSUE TITLE
Update VSF project

### ISSUE THREAD

**Issue by MajorKuprich** [vuestorefront/magento2#1038]
### What is your question / Please describe your issue

Hello,

How are You?

Is it known how to update the VSF project? 
I mean a command that will allow us to update VSF from version e.g. 2.1 to 2.2?

In VSF 1.x I found docs about this.
Unfortunately it contains only introduction. :(

### What version of Magento 2 Integration are you using?

Magento 2.4.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
Hi, 

VSF2 is a boilerplate, so it's hard to say how to update it because everyone can use the code differently. 

In terms of documentation, we only have release notes and breaking change reference documents, example:=https://docs.vuestorefront.io/magento/migration-guides/1.0.0-rc.9/

So basically, you can check what changed in a specific version and apply changes to your code if you need them.

**Comment by davidwindell** [comment]
I'd love to see a more sustainable approach being taken to this.

I.e. a future where VSF is much more extensible without having to override the boilerplate.

Coming from a Magento background where we only have to keep our custom changes in a repository and upgrades are as easy as a composer.json version change, it would be hugely beneficial.

**Comment by Frodigo** [comment]
Thanks for your feedback, @davidwindell! 

For now, I close this issue.  Feel free to re-open if you have more questions.

Thanks,
Marcin
