### ISSUE TITLE
[Question] How to handle payments through external payment providers?

### ISSUE THREAD

**Issue by tafelnl** [vuestorefront/magento2#132]
### What is your question / Please describe your issue

How can we handle payments through external payment providers (e.g. Adyen, Stripe, Mollie)? It could be that I am asking this question in the wrong place, since it might apply to Vue Storefront in general. But since every integration could handle payments different, I figured I should ask it here.

Imagine I want to implement iDEAL by Mollie payments to finalize an order. How would I go about that? I cannot find much documentation about this.

### What version of Magento 2 Integration are you using?

1.0.0-rc.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
It's being developed the external checkout plugin by the guys over [Caravel](https://github.com/caravelx) and it's planned to be released soon. It's been tested and finished with some details.

When it's ready, I will post the plugin links here, and add the information on the README.md

**Comment by Frodigo** [comment]
@bloodf any updates about the plugin you mentioned above?

**Comment by jonathanribas** [comment]
Hi @Frodigo, any update regarding the external checkout? 
How can a stable version can be released without a checkout?

**Comment by Frodigo** [comment]
Hi @jonathanribas, for the 1.0.0 version external checkout won't be supported. 
There is more work on the Magento module side and we plan to work on that when we resolve issues with performance.

Anyway, it does not prevent us from releasing a stable version because we have a fully functional internal checkout.
In addition, we offer an external module for Ayden payments: https://docs.vuestorefront.io/adyen/magento2/ 

Thanks,
Marcin Kwiatkowski

**Comment by jonathanribas** [comment]
Hi @Frodigo, didn't know about this! 
Great news, we will test it.
